- app.go
- go.mod
- go.sum
- main.go
- status.go
- vice.go
Monitors k8s events for pods and deployments in the vice-apps namespace and forwards them on as notifications through the job-status-listener service.
> Monitor K8s events

- vice.go
This time around, we're simply going to reject attempts to launch VICE jobs when the user has reached their concurrent job limit.
> CORE-660: VICE job limits initial implementation

- apps/main.go
Turns ip_address into an empty string if the value from the database ends up being null. Scans for a sql.NullString instead of a string in the query that was breaking.
> Account for ip_address possibly being null

- internal/internal.go
- internal/limits.go
- internal/limits_test.go
Usernames containing hyphens and underscores have been problematic for us when we're doing limit checks. This was occurring because the username that we were using to query the database was not necessarily the actual username. This change fixes that problem and adds some more unit tests.
The change to fix the problem involves some special processing for usernames containing leading and trailing hyphens or underscores in an attempt to make it fairly unlikely that the pod label values for two different usernames will be the same, which would also break concurrency limit checks.
> CORE-1286: fix a bug in concurrent job limit checks for usernames containing underscores

- app.go
- instantlaunches/defaults_test.go
- instantlaunches/main.go
- instantlaunches/metadata.go
- main.go
Adds fairly basic proxy endpoints to metadata that manage AVUs specifically for instant launches.
> Add Instant Launch metadata management endpoints

- internal/deployments.go
I decided to look and this is actually pretty easy to do, assuming I didn't screw something up, and will make the hostnames shown in terminals and stuff way shorter (and match the URL in the address bar). It at least compiles, but I admit I didn't really test it further just yet since it's not really on-task for me :)
> Use the 'nice' Ingress name as the pod hostname, hopefully

- go.mod
- go.sum
- instantlaunches/db.go
- instantlaunches/defaults.go
- instantlaunches/main.go
- instantlaunches/metadata.go
- instantlaunches/mgmt.go
- instantlaunches/users.go
In this case, I mean actionable to mean that a caller can grab submission, quick launch, and instant launch information in a single request, allowing the caller to submit an instant launch job without having to perform separate requests for each piece of information.
This adds the `/instantlaunches/:id/full` endpoint, which returns the info for a single instant launch, and the `/instantlaunches/metadata/full`, which returns a listing of that info for multiple instant launches based on the metadata passed in.
> Add actionable instant launch endpoints

- instantlaunches/db.go
- instantlaunches/main.go
- instantlaunches/mgmt.go
Our current quick launch listing endpoint will list all quick launch regardless of whether its app is public or not. This endpoint only lists quick launches if they're public and the app is public.
> Add endpoint to list quicklaunches for public apps

- app.go
- internal/deployments.go
- internal/internal.go
- main.go
I think this should work -- pretty sure if it's not configured, it'll just get an empty string and then configure nothing, which is probably what we want.
> Use an image pull secret name provided from the configuration file to configure imagePullSecrets for VICE deployments

- internal/volumes.go
App Exposer should use "Retain" for reclaim policy since it deletes `PV` manually.
Otherwise, it errors following when it tries to delete `PV` and fails.
```
Message:         error getting deleter volume plugin for volume "csi-home-volume-b0229fda-d810-4ac0-a253-14384fa9cd89": no deletable volume plugin matched
```
> Change PV reclaim policy from reclaim to retain for manual deletion

- apps/main.go
- internal/deployments.go
- internal/internal.go
- internal/volumes.go
Updates the jobs.millicores_reserved column in the database with the value found in the job submission. Also, refactors some of the code that sets the limits and requests in the deployment so it's a bit easier to follow.
> Set the millicores_reserved value for each submitted job.

- apps/apps.go
- go.mod
- go.sum
- internal/internal.go
Switch over to apd.Decimal to maintain precision when dealing with code related to CPU hours calculations.
> Switch over to apd.Decimal

- app.go
- apps/apps.go
- configs/default.yml
- instantlaunches/db.go
- instantlaunches/main.go
- internal/constants.go
- internal/deployments.go
- internal/internal.go
- internal/limits_test.go
- internal/transfers.go
- internal/volumes.go
- main.go
The purpose of this change is to address some support requests that we've received since the iRODS CSI driver was moved to production. With the CSI driver enabled, the input data location isn't as intuitive as it was before, so we're hoping that adding symbolic links to the working directory configured in the tool definition for the app will help. The symbolic links will be defined as follows.
| Name | Target | Description |
| ------ | ------ | ------------ |
| data | /data | The parent directory of both the input data folder and the analysis output folder. |
| home | /{zone}/home | The parent directory of the user's home folder and the community data folder in the data store. |
> CORE-1667: data access improvements for VICE with iRODS CSI Driver integration enabled

- go.mod
- internal/status.go
- main.go
The removed code is being moved into the new vice-status-listener service. The rest of the job status listener related code in this repo is still being used to update the job status at different points in the analyses's lifetimes, so it needs to stick around.
> Remove deployment event monitoring

- internal/volumes.go
This bypasses permission check (ACLs listing) to improve performance.
The permission check is not required for CyVerse DE since we always provide ReadWrite for users' home and Readonly for shared dir.
> Set no permission check for performance

- instantlaunches/db.go
- instantlaunches/main.go
Adds an `app_version` label to the following endpoint responses:
* GET /instantlaunches/full
* GET /instantlaunches/metadata/full
* GET /instantlaunches/:id/full
> CORE-1809 Update /instantlaunches/*full endpoints with app version

- internal/limits.go
We need to only guard against cpu.hours overages in app-exposer. We don't care about data.size overages here.
> Add guard check for the resource name for overage detection

- internal/internal.go
I think this is the fix for the time-limit endpoint issue. The timestamps in the DB were set correctly, but the way we were reading them in assumed UTC, where they are actually local timestamps. Calling `.Local()` doesn't change timestamps in go, merely marks them as belonging to the local timezone, so this should cause them to start being returned correctly after being converted to unix epoch values.
> Mark the planned end date read from the database as a local timestamp

- instantlaunches/main.go
- instantlaunches/metadata.go
- instantlaunches/mgmt.go
This still needs some testing, but I think should be basically done. This:
* Moves the existing endpoints, which are really admin-only endpoints, into an `admin` path.
* Where applicable (i.e. for add/update/delete, but not for metadata stuff), adds new endpoints at the locations of the old ones that expect a `user` to be passed in and verify that the user matches that in the submission or in the existing database entry. (This user parameter will be added by terrain from auth information)
> Add non-admin/admin version split for instant launches, to allow users to create/update/delete

- internal/constants.go
- internal/deployments.go
This change allows DE administrators to indicate that an app should have shared memory allocated to it for tools that require shared memory. We provide the shared memory by creating an emptyDir volume with the size limit specified by the tool. (See this [StackOverflow answer](https://stackoverflow.com/a/46434614/299222) for more details.)
This is implemented in a similar way to our GPU integration. To dedicate shared memory to a tool add a container device to the tool with a host path of `/dev/shm` and a container path equal to the amount of shared memory to make available:
It's not a perfect way to indicate how much shared memory should be provided, but implementing it this way allowed us to make this feature available quickly.
> CORE-2026: allocate shared memory if the tool is configured to use it

- internal/deployments.go
The absence of requests and limits are sometimes causing pods to be evicted unnecessarily.
> CORE-2032: added resource requests to the vice-proxy container

- adapter/adapter.go
- batch/batch.go
- cmd/app-exposer/main.go
- cmd/workflow-builder/main.go
- go.mod
- go.sum
Adds support for data containers as secrets mounted into a batch workflow.
The name prefix stored in the database becomes the name of the volume. 
The names of the secrets are expected to conform to slugification rules, with the exception that underscores are replaced with dashes. 
The mount point of the secret is the data container's container path. 
The path each key is mounted at under the container path is specified in the secret's annotations, with each data key having a corresponding annotation whose value is the path to the file under the mount point.
> Add support for data containers as secrets mounted into a batch workflow

- incluster/internal.go
- incluster/pdb.go
Adds a pod disruption budget that allows for 0 pods being unavailable. This will hopefully cut down on the number of evictions we see.
> Add pod disruption budget for the VICE pods

- adapter/adapter.go
- apps/apps.go
- cmd/app-exposer/app.go
- cmd/app-exposer/main.go
- constants/constants.go
- db/db.go
- go.mod
- httphandlers/batch.go
- httphandlers/exit.go
- httphandlers/handlers.go
- httphandlers/resources.go
- httphandlers/timelimit.go
This does a bit more than it says in the subject. In order to get sane database access I had to move some types around. I moved the HTTP handlers for the batch analyses into httphandlers and adjusted things from there. The main logic for the handler in question is in exit.go.
> Add handler to kill all running VICE and batch jobs

- adapter/adapter.go
- quota/enforcer.go
This PR splits up the logic for quota enforcement between batch and VICE analyses.
VICE analyses enforce a maximum number of concurrently running analyses. Batch analyses do not. Both enforce resource usage limits.
> Enforce overages but not analysis number limits for batch analyses

- adapter/adapter.go
- batch/batch.go
- cmd/app-exposer/main.go
- cmd/workflow-builder/main.go
We're using a new image to implement the logic for the exit handler. It should allow the logic to always send the analysis status even if uploads fail for some reason.
> Use batch-exit-handler image, remove flag to disable cleanup
